# Generated by Django 5.2.2 on 2026-07-26 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_store_latitude_store_longitude_alter_brand_id_and_more'),
        ('orders', '0007_alter_order_id_alter_order_status_alter_orderitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('OPENING_BALANCE', 'Saldo inicial'), ('RECEIPT', 'Recepción'), ('ADJUSTMENT', 'Ajuste'), ('COUNT_CORRECTION', 'Corrección de conteo'), ('ORDER_DEDUCT', 'Descuento de pedido')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.warehouse')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'id'], name='catalog_sto_product_138832_idx')],
            },
        ),
    ]
