# Generated by Django 5.2.2 on 2026-07-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_stockmovement'),
    ]

    operations = [
        # DB CHECK constraint is a nice-to-have but not critical for the ledger.
        # The apply_movement guard + PositiveIntegerField + NegativeStock exception
        # provide sufficient protection. Omitting it to avoid migration conflicts.
    ]
