# Generated by Django 6.0.6 on 2026-07-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='photo_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
