# Generated by Django 5.2.2 on 2026-07-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_deliveryconfirmation_photo_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
