# Generated by Django 6.0.6 on 2026-07-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='issue_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20),
        ),
    ]
