# Generated by Django 6.0.6 on 2026-07-19 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_active_product_low_stock_threshold_and_more'),
        ('orders', '0003_order_issue_description_order_issue_reported_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'status'], name='orders_orde_vendor__d2c878_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store'], name='orders_orde_store_i_6ed055_idx'),
        ),
    ]
