# Generated by Django 6.0.6 on 2026-07-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
