# Generated by Django 5.2.2 on 2026-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_distributorinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratis'), ('STANDARD', 'Estándar'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='distributor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('TRIAL', 'Prueba'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distributorinvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('DISTRIBUTOR', 'Distributor'), ('STORE_OWNER', 'Store Owner'), ('VENDOR', 'Vendor'), ('DELIVERY', 'Delivery')], max_length=20),
        ),
    ]
