# Generated by Django 5.2.2 on 2026-07-26 04:38

from django.db import migrations
from django.utils import timezone


def seed_opening_balances(apps, schema_editor):
    """Backfill one OPENING_BALANCE movement per existing StockLevel."""
    StockLevel = apps.get_model('catalog', 'StockLevel')
    StockMovement = apps.get_model('catalog', 'StockMovement')

    for sl in StockLevel.objects.all():
        StockMovement.objects.create(
            product=sl.product,
            warehouse=sl.warehouse,
            delta=sl.quantity,
            reason='OPENING_BALANCE',
            actor=None,
            order=None,
            balance_after=sl.quantity,
            created_at=timezone.now(),
        )


def reverse_opening_balances(apps, schema_editor):
    """Remove all OPENING_BALANCE movements."""
    StockMovement = apps.get_model('catalog', 'StockMovement')
    StockMovement.objects.filter(reason='OPENING_BALANCE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_quantity_check'),
    ]

    operations = [
        migrations.RunPython(seed_opening_balances, reverse_opening_balances),
    ]
