# Generated by Django 5.2.2 on 2026-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliveryconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
