# Generated by Django 5.2.2 on 2026-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_distributor_plan_distributor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Súper Admin'), ('DISTRIBUTOR', 'Distribuidor'), ('STORE_OWNER', 'Dueño de Tienda'), ('VENDOR', 'Vendedor'), ('DELIVERY', 'Repartidor')], max_length=20),
        ),
    ]
